# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
trigger:
- master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
- group: app-group
stages:
- stage: demostage
  jobs:
  - job: Test
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure Pass – Sponsorship (bac07c89-b922-4896-882f-359d1cfd5058)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm create --resource-group classdemo --name demovm3 --image win2019datacenter --admin-username demousr --admin-password $(vmpassword)'